'use strict';

const APP_DATA = {
  meta: {
    lastRefreshed: '2026-07-15T17:15:00+05:30',
    date: '2026-07-15',
    dateLabel: 'Jul 15, 2026',
  },

  health: {
    totalOrders: 18542,
    ordersDelta: '+3.2%',
    ordersDeltaDir: 'up',
    activeRiders: 1247,
    ridersAvailable: 892,
    ridersBusy: 355,
    liveStores: 89,
    totalStores: 94,
    offlineStores: 5,
    citiesLive: 24,
    pendingCOD: 482350,
    slaAtRisk: 312,
    slaAtRiskPct: 1.68,
    openExceptions: 47,
    criticalExceptions: 12,
    carrierOutages: 3,
    activeOutages: 2,
  },

  orderStates: [
    { label: 'All Orders',        value: 18542, pct: null, active: true  },
    { label: 'Created',           value: 2847,  pct: 15.4              },
    { label: 'Assigned',          value: 3124,  pct: 16.9              },
    { label: 'Picked Up',         value: 2891,  pct: 15.6              },
    { label: 'Out For Delivery',  value: 4218,  pct: 22.7              },
    { label: 'Delivered',         value: 4109,  pct: 22.2              },
    { label: 'Failed',            value: 891,   pct: 4.8               },
    { label: 'Returned',          value: 318,   pct: 1.7               },
    { label: 'Cancelled',         value: 144,   pct: 0.8               },
  ],

  cities: [
    { city: 'Mumbai',    stores: 18, riders: 287, orders: 3847, delivered: 2140, failed: 143, otd: 89.2, slaRisk: 45, exceptions: 8,  health: 'good'     },
    { city: 'Delhi NCR', stores: 14, riders: 198, orders: 2914, delivered: 1520, failed: 178, otd: 82.3, slaRisk: 67, exceptions: 14, health: 'warning'  },
    { city: 'Bangalore', stores: 12, riders: 167, orders: 2341, delivered: 1580, failed: 87,  otd: 91.4, slaRisk: 23, exceptions: 5,  health: 'good'     },
    { city: 'Hyderabad', stores: 9,  riders: 134, orders: 1872, delivered: 980,  failed: 112, otd: 83.1, slaRisk: 38, exceptions: 7,  health: 'warning'  },
    { city: 'Chennai',   stores: 8,  riders: 121, orders: 1654, delivered: 1020, failed: 71,  otd: 87.8, slaRisk: 19, exceptions: 3,  health: 'good'     },
    { city: 'Pune',      stores: 7,  riders: 98,  orders: 1421, delivered: 890,  failed: 58,  otd: 91.2, slaRisk: 14, exceptions: 2,  health: 'good'     },
    { city: 'Kolkata',   stores: 6,  riders: 89,  orders: 1247, delivered: 720,  failed: 68,  otd: 84.3, slaRisk: 22, exceptions: 4,  health: 'good'     },
    { city: 'Ahmedabad', stores: 5,  riders: 67,  orders: 987,  delivered: 580,  failed: 44,  otd: 86.5, slaRisk: 18, exceptions: 2,  health: 'good'     },
    { city: 'Surat',     stores: 4,  riders: 54,  orders: 743,  delivered: 410,  failed: 47,  otd: 82.9, slaRisk: 31, exceptions: 6,  health: 'warning'  },
    { city: 'Jaipur',    stores: 3,  riders: 32,  orders: 516,  delivered: 269,  failed: 42,  otd: 77.3, slaRisk: 35, exceptions: 6,  health: 'critical' },
  ],

  stores: [
    { store: 'Reliance Smart - Andheri',  city: 'Mumbai',    carrier: 'Bluedart',   riders: 12, orders: 287, delivered: 198, failed: 23, status: 'Active'  },
    { store: 'BigBasket - Dwarka',        city: 'Delhi NCR', carrier: 'DTDC',       riders: 8,  orders: 214, delivered: 140, failed: 32, status: 'Active'  },
    { store: 'More Supermarket - HITEC',  city: 'Hyderabad', carrier: 'Delhivery',  riders: 6,  orders: 187, delivered: 110, failed: 28, status: 'Active'  },
    { store: 'D-Mart - Vasant Kunj',      city: 'Delhi NCR', carrier: 'DTDC',       riders: 7,  orders: 204, delivered: 130, failed: 35, status: 'Active'  },
    { store: 'Star Bazaar - Thane',       city: 'Mumbai',    carrier: 'Bluedart',   riders: 9,  orders: 198, delivered: 143, failed: 18, status: 'Active'  },
    { store: 'Spencers - C-Scheme',       city: 'Jaipur',    carrier: 'Ekart',      riders: 4,  orders: 98,  delivered: 52,  failed: 20, status: 'Active'  },
    { store: 'Hypercity - Whitefield',    city: 'Bangalore', carrier: 'Delhivery',  riders: 6,  orders: 176, delivered: 130, failed: 14, status: 'Active'  },
    { store: 'Natures Basket - Ring Rd',  city: 'Surat',     carrier: 'Xpressbees', riders: 4,  orders: 124, delivered: 81,  failed: 19, status: 'Active'  },
    { store: 'FoodHall - Vasant Vihar',   city: 'Delhi NCR', carrier: 'DTDC',       riders: 5,  orders: 143, delivered: 89,  failed: 22, status: 'Active'  },
    { store: 'Zara - Phoenix - Pune',     city: 'Pune',      carrier: 'Ekart',      riders: 0,  orders: 0,   delivered: 0,   failed: 0,  status: 'Offline' },
    { store: 'H&M - DLF - Gurgaon',      city: 'Delhi NCR', carrier: 'DTDC',       riders: 0,  orders: 0,   delivered: 0,   failed: 0,  status: 'Offline' },
    { store: 'SPAR - Whitefield',         city: 'Bangalore', carrier: 'Delhivery',  riders: 0,  orders: 0,   delivered: 0,   failed: 0,  status: 'Offline' },
    { store: 'Le Marche - Koregaon',      city: 'Pune',      carrier: 'Ekart',      riders: 7,  orders: 164, delivered: 110, failed: 14, status: 'Active'  },
    { store: 'Easyday - Salt Lake',       city: 'Kolkata',   carrier: 'Xpressbees', riders: 5,  orders: 138, delivered: 89,  failed: 18, status: 'Active'  },
    { store: 'Metro Cash - Andheri',      city: 'Mumbai',    carrier: 'Bluedart',   riders: 0,  orders: 0,   delivered: 0,   failed: 0,  status: 'Offline' },
  ],

  slaRisk: [
    { orderId: 'ORD-MUM-2847392', store: 'Reliance Smart - Andheri', city: 'Mumbai',    customer: 'Priya Sharma',  promised: '03:30 PM', current: '05:45 PM', delay: '+135 min', carrier: 'Bluedart',   risk: 'Critical' },
    { orderId: 'ORD-DEL-1923847', store: 'BigBasket - Dwarka',       city: 'Delhi NCR', customer: 'Rohit Mehta',   promised: '02:00 PM', current: '04:10 PM', delay: '+130 min', carrier: 'DTDC',       risk: 'Critical' },
    { orderId: 'ORD-DEL-1923912', store: 'D-Mart - Vasant Kunj',     city: 'Delhi NCR', customer: 'Anita Singh',   promised: '04:00 PM', current: '05:50 PM', delay: '+110 min', carrier: 'DTDC',       risk: 'Critical' },
    { orderId: 'ORD-JAI-0312847', store: 'Spencers - C-Scheme',      city: 'Jaipur',    customer: 'Meera Agarwal', promised: '02:30 PM', current: '05:00 PM', delay: '+150 min', carrier: 'Ekart',      risk: 'Critical' },
    { orderId: 'ORD-HYD-0847231', store: 'More Supermarket - HITEC', city: 'Hyderabad', customer: 'Kiran Reddy',   promised: '03:00 PM', current: '04:55 PM', delay: '+115 min', carrier: 'Delhivery',  risk: 'High'     },
    { orderId: 'ORD-MUM-2847501', store: 'Star Bazaar - Thane',      city: 'Mumbai',    customer: 'Vikram Joshi',  promised: '04:30 PM', current: '06:15 PM', delay: '+105 min', carrier: 'Bluedart',   risk: 'High'     },
    { orderId: 'ORD-SUR-0123491', store: 'Natures Basket - Ring Rd', city: 'Surat',     customer: 'Dinesh Patel',  promised: '03:45 PM', current: '05:30 PM', delay: '+105 min', carrier: 'Xpressbees', risk: 'High'     },
    { orderId: 'ORD-DEL-1924081', store: 'FoodHall - Vasant Vihar',  city: 'Delhi NCR', customer: 'Sunita Kapoor', promised: '05:00 PM', current: '06:45 PM', delay: '+105 min', carrier: 'DTDC',       risk: 'High'     },
    { orderId: 'ORD-BLR-0918274', store: 'Hypercity - Whitefield',   city: 'Bangalore', customer: 'Ravi Kumar',    promised: '05:30 PM', current: '07:00 PM', delay: '+90 min',  carrier: 'Delhivery',  risk: 'Medium'   },
    { orderId: 'ORD-PUN-0429184', store: 'Le Marche - Koregaon',     city: 'Pune',      customer: 'Smita Desai',   promised: '06:00 PM', current: '07:25 PM', delay: '+85 min',  carrier: 'Ekart',      risk: 'Medium'   },
  ],

  exceptions: [
    { id: 'EXC-0014782', type: 'Carrier Outage',        related: 'Bluedart - Mumbai',      city: 'Mumbai',    severity: 'Critical', raised: '11:30 AM', status: 'Open',        assignee: 'Ops Team'   },
    { id: 'EXC-0014783', type: 'Carrier Outage',        related: 'DTDC - Delhi NCR',       city: 'Delhi NCR', severity: 'Critical', raised: '02:15 PM', status: 'Open',        assignee: 'Ops Team'   },
    { id: 'EXC-0014835', type: 'Store Offline',         related: 'Zara - Phoenix - Pune',  city: 'Pune',      severity: 'Critical', raised: '04:30 PM', status: 'Open',        assignee: 'Store Ops'  },
    { id: 'EXC-0014791', type: 'Vehicle Breakdown',     related: 'ORD-MUM-2847501',        city: 'Mumbai',    severity: 'High',     raised: '01:45 PM', status: 'In Progress', assignee: 'Amit Kumar' },
    { id: 'EXC-0014798', type: 'Address Issue',         related: 'ORD-JAI-0312847',        city: 'Jaipur',    severity: 'High',     raised: '12:20 PM', status: 'Open',        assignee: 'Unassigned' },
    { id: 'EXC-0014819', type: 'Package Damage',        related: 'ORD-HYD-0847231',        city: 'Hyderabad', severity: 'High',     raised: '02:55 PM', status: 'In Progress', assignee: 'QC Team'    },
    { id: 'EXC-0014812', type: 'Customer Unavailable',  related: 'ORD-DEL-1923847',        city: 'Delhi NCR', severity: 'Medium',   raised: '03:10 PM', status: 'Open',        assignee: 'Unassigned' },
    { id: 'EXC-0014823', type: 'Payment Failed',        related: 'ORD-SUR-0123491',        city: 'Surat',     severity: 'Medium',   raised: '03:40 PM', status: 'Open',        assignee: 'Finance'    },
    { id: 'EXC-0014840', type: 'COD Collection Failed', related: 'ORD-BLR-0918274',        city: 'Bangalore', severity: 'Medium',   raised: '05:00 PM', status: 'Open',        assignee: 'Finance'    },
    { id: 'EXC-0014831', type: 'Geo-fence Breach',      related: 'RDR-MUM-4821',           city: 'Mumbai',    severity: 'Low',      raised: '04:05 PM', status: 'Monitoring',  assignee: 'Ops Team'   },
  ],

  carrierOutages: [
    {
      carrier: 'Bluedart',
      region: 'Mumbai Metro',
      affectedOrders: 234,
      status: 'Active',
      since: '11:30 AM',
      eta: '07:00 PM',
      cities: ['Mumbai', 'Thane', 'Navi Mumbai'],
    },
    {
      carrier: 'DTDC',
      region: 'Delhi NCR',
      affectedOrders: 178,
      status: 'Monitoring',
      since: '02:15 PM',
      eta: '06:30 PM',
      cities: ['New Delhi', 'Gurgaon', 'Noida'],
    },
    {
      carrier: 'Delhivery',
      region: 'Hyderabad',
      affectedOrders: 156,
      status: 'Resolved',
      since: '12:00 PM',
      eta: '03:45 PM',
      cities: ['Hyderabad', 'Secunderabad'],
    },
  ],

  pendingCOD: [
    { store: 'Reliance Smart - Andheri', city: 'Mumbai',    amount: 84250, orders: 47, oldest: '2026-07-13', daysOld: 2, status: 'Overdue'   },
    { store: 'BigBasket - Dwarka',       city: 'Delhi NCR', amount: 71840, orders: 38, oldest: '2026-07-14', daysOld: 1, status: 'Due Today' },
    { store: 'More Supermarket - HITEC', city: 'Hyderabad', amount: 63420, orders: 31, oldest: '2026-07-13', daysOld: 2, status: 'Overdue'   },
    { store: 'D-Mart - Vasant Kunj',     city: 'Delhi NCR', amount: 58900, orders: 29, oldest: '2026-07-14', daysOld: 1, status: 'Due Today' },
    { store: 'Star Bazaar - Thane',      city: 'Mumbai',    amount: 47320, orders: 24, oldest: '2026-07-12', daysOld: 3, status: 'Overdue'   },
    { store: 'Spencers - C-Scheme',      city: 'Jaipur',    amount: 43890, orders: 21, oldest: '2026-07-14', daysOld: 1, status: 'Due Today' },
    { store: 'Hypercity - Whitefield',   city: 'Bangalore', amount: 38140, orders: 19, oldest: '2026-07-15', daysOld: 0, status: 'Pending'   },
    { store: 'Natures Basket - Ring Rd', city: 'Surat',     amount: 34780, orders: 17, oldest: '2026-07-14', daysOld: 1, status: 'Due Today' },
    { store: 'FoodHall - Vasant Vihar',  city: 'Delhi NCR', amount: 28960, orders: 14, oldest: '2026-07-15', daysOld: 0, status: 'Pending'   },
    { store: 'Le Marche - Koregaon',     city: 'Pune',      amount: 10850, orders: 6,  oldest: '2026-07-15', daysOld: 0, status: 'Pending'   },
  ],
};
