'use strict';

const APP_DATA = {
  meta: {
    lastRefreshed: '2026-07-15T17:15:00+05:30',
    date: '2026-07-15',
    dateLabel: 'Jul 15, 2026',
  },

  health: {
    totalOrders: 18542,
    ordersDelta: '+3.2%',
    ordersDeltaDir: 'up',
    activeRiders: 1247,
    ridersAvailable: 892,
    ridersBusy: 355,
    liveStores: 89,
    totalStores: 94,
    offlineStores: 5,
    citiesLive: 24,
    pendingCOD: 482350,
    slaAtRisk: 312,
    slaAtRiskPct: 1.68,
  },

  orderStates: [
    { label: 'All Orders',        value: 18542, pct: null, active: true  },
    { label: 'Created',           value: 2847,  pct: 15.4              },
    { label: 'Assigned',          value: 3124,  pct: 16.9              },
    { label: 'Picked Up',         value: 2891,  pct: 15.6              },
    { label: 'Out For Delivery',  value: 4218,  pct: 22.7              },
    { label: 'Delivered',         value: 4109,  pct: 22.2              },
    { label: 'Failed',            value: 891,   pct: 4.8               },
    { label: 'Returned',          value: 318,   pct: 1.7               },
    { label: 'Cancelled',         value: 144,   pct: 0.8               },
  ],

  cities: [
    { city: 'Mumbai',    stores: 26, riders: 287, orders: 4847, delivered: 1140, failed: 153, otd: 89.2, slaRisk: 45, exceptions: 4,  health: 'good'     },
    { city: 'Delhi NCR', stores: 14, riders: 198, orders: 2914, delivered: 620,  failed: 188, otd: 82.3, slaRisk: 67, exceptions: 11, health: 'warning'  },
    { city: 'Bangalore', stores: 12, riders: 167, orders: 2341, delivered: 580,  failed: 97,  otd: 91.4, slaRisk: 23, exceptions: 5,  health: 'good'     },
    { city: 'Hyderabad', stores: 9,  riders: 134, orders: 1872, delivered: 380,  failed: 123, otd: 83.1, slaRisk: 38, exceptions: 4,  health: 'warning'  },
    { city: 'Chennai',   stores: 8,  riders: 121, orders: 1654, delivered: 420,  failed: 71,  otd: 87.8, slaRisk: 19, exceptions: 3,  health: 'good'     },
    { city: 'Pune',      stores: 7,  riders: 98,  orders: 1421, delivered: 290,  failed: 58,  otd: 91.2, slaRisk: 14, exceptions: 2,  health: 'good'     },
    { city: 'Kolkata',   stores: 6,  riders: 89,  orders: 1247, delivered: 220,  failed: 68,  otd: 84.3, slaRisk: 22, exceptions: 4,  health: 'good'     },
    { city: 'Ahmedabad', stores: 5,  riders: 67,  orders: 987,  delivered: 180,  failed: 44,  otd: 86.5, slaRisk: 18, exceptions: 2,  health: 'good'     },
    { city: 'Surat',     stores: 4,  riders: 54,  orders: 743,  delivered: 110,  failed: 47,  otd: 82.9, slaRisk: 31, exceptions: 6,  health: 'warning'  },
    { city: 'Jaipur',    stores: 3,  riders: 32,  orders: 516,  delivered: 169,  failed: 42,  otd: 77.3, slaRisk: 35, exceptions: 6,  health: 'critical' },
  ],

  stores: [
    { store: 'STR-MUM-01 - Andheri',      city: 'Mumbai',    carrier: 'Ownfleet',   riders: 12, orders: 287, delivered: 198, failed: 23, status: 'Active'  },
    { store: 'STR-DEL-01 - Dwarka',       city: 'Delhi NCR', carrier: 'Ownfleet',   riders: 8,  orders: 214, delivered: 140, failed: 32, status: 'Active'  },
    { store: 'STR-HYD-01 - HITEC',        city: 'Hyderabad', carrier: 'Ownfleet',   riders: 6,  orders: 187, delivered: 110, failed: 28, status: 'Active'  },
    { store: 'STR-DEL-02 - Vasant Kunj',  city: 'Delhi NCR', carrier: 'Ownfleet',   riders: 7,  orders: 204, delivered: 130, failed: 35, status: 'Active'  },
    { store: 'STR-MUM-02 - Thane',        city: 'Mumbai',    carrier: 'Ownfleet',   riders: 9,  orders: 198, delivered: 143, failed: 18, status: 'Active'  },
    { store: 'STR-JAI-01 - C-Scheme',     city: 'Jaipur',    carrier: 'Ownfleet',   riders: 4,  orders: 98,  delivered: 52,  failed: 20, status: 'Active'  },
    { store: 'STR-BLR-01 - Whitefield',   city: 'Bangalore', carrier: 'Shadowfax',  riders: 6,  orders: 176, delivered: 130, failed: 14, status: 'Active'  },
    { store: 'STR-SUR-01 - Ring Rd',      city: 'Surat',     carrier: 'Shadowfax',  riders: 4,  orders: 124, delivered: 81,  failed: 19, status: 'Active'  },
    { store: 'STR-DEL-03 - Vasant Vihar', city: 'Delhi NCR', carrier: 'Delhivery',  riders: 5,  orders: 143, delivered: 89,  failed: 22, status: 'Active'  },
    { store: 'STR-PUN-01 - Phoenix',      city: 'Pune',      carrier: 'Delhivery',  riders: 0,  orders: 0,   delivered: 0,   failed: 0,  status: 'Offline' },
    { store: 'STR-DEL-04 - Gurgaon',      city: 'Delhi NCR', carrier: 'Borzo',      riders: 0,  orders: 0,   delivered: 0,   failed: 0,  status: 'Offline' },
    { store: 'STR-BLR-02 - Whitefield',   city: 'Bangalore', carrier: 'Borzo',      riders: 0,  orders: 0,   delivered: 0,   failed: 0,  status: 'Offline' },
    { store: 'STR-PUN-02 - Koregaon',     city: 'Pune',      carrier: 'Rapido',     riders: 7,  orders: 164, delivered: 110, failed: 14, status: 'Active'  },
    { store: 'STR-KOL-01 - Salt Lake',    city: 'Kolkata',   carrier: 'Rapido',     riders: 0,  orders: 0,   delivered: 0,   failed: 0,  status: 'Offline' },
    { store: 'STR-MUM-03 - Andheri',      city: 'Mumbai',    carrier: 'Rapido',     riders: 0,  orders: 0,   delivered: 0,   failed: 0,  status: 'Offline' },
  ],

  slaRisk: [
    { orderId: 'ORD-MUM-2847392', store: 'STR-MUM-01 - Andheri',      city: 'Mumbai',    customer: 'Priya Sharma',  promised: '03:30 PM', current: '05:45 PM', delay: '+135 min', carrier: 'Ownfleet',   risk: 'Critical' },
    { orderId: 'ORD-DEL-1923847', store: 'STR-DEL-01 - Dwarka',       city: 'Delhi NCR', customer: 'Rohit Mehta',   promised: '02:00 PM', current: '04:10 PM', delay: '+130 min', carrier: 'Ownfleet',   risk: 'Critical' },
    { orderId: 'ORD-DEL-1923912', store: 'STR-DEL-02 - Vasant Kunj',  city: 'Delhi NCR', customer: 'Anita Singh',   promised: '04:00 PM', current: '05:50 PM', delay: '+110 min', carrier: 'Ownfleet',   risk: 'Critical' },
    { orderId: 'ORD-JAI-0312847', store: 'STR-JAI-01 - C-Scheme',     city: 'Jaipur',    customer: 'Meera Agarwal', promised: '02:30 PM', current: '05:00 PM', delay: '+150 min', carrier: 'Ownfleet',   risk: 'Critical' },
    { orderId: 'ORD-HYD-0847231', store: 'STR-HYD-01 - HITEC',        city: 'Hyderabad', customer: 'Kiran Reddy',   promised: '03:00 PM', current: '04:55 PM', delay: '+115 min', carrier: 'Shadowfax',  risk: 'High'     },
    { orderId: 'ORD-MUM-2847501', store: 'STR-MUM-02 - Thane',        city: 'Mumbai',    customer: 'Vikram Joshi',  promised: '04:30 PM', current: '06:15 PM', delay: '+105 min', carrier: 'Shadowfax',  risk: 'High'     },
    { orderId: 'ORD-SUR-0123491', store: 'STR-SUR-01 - Ring Rd',      city: 'Surat',     customer: 'Dinesh Patel',  promised: '03:45 PM', current: '05:30 PM', delay: '+105 min', carrier: 'Delhivery',  risk: 'High'     },
    { orderId: 'ORD-DEL-1924081', store: 'STR-DEL-03 - Vasant Vihar', city: 'Delhi NCR', customer: 'Sunita Kapoor', promised: '05:00 PM', current: '06:45 PM', delay: '+105 min', carrier: 'Delhivery',  risk: 'High'     },
    { orderId: 'ORD-BLR-0918274', store: 'STR-BLR-01 - Whitefield',   city: 'Bangalore', customer: 'Ravi Kumar',    promised: '05:30 PM', current: '07:00 PM', delay: '+90 min',  carrier: 'Borzo',      risk: 'Medium'   },
    { orderId: 'ORD-PUN-0429184', store: 'STR-PUN-02 - Koregaon',     city: 'Pune',      customer: 'Smita Desai',   promised: '06:00 PM', current: '07:25 PM', delay: '+85 min',  carrier: 'Rapido',     risk: 'Medium'   },
    { orderId: 'ORD-MUM-2847393', store: 'STR-MUM-01 - Andheri',      city: 'Mumbai',    customer: 'Amit Patel',    promised: '03:45 PM', current: '05:50 PM', delay: '+125 min', carrier: 'Ownfleet',   risk: 'Critical' },
    { orderId: 'ORD-DEL-1923848', store: 'STR-DEL-01 - Dwarka',       city: 'Delhi NCR', customer: 'Sneha Gupta',   promised: '02:15 PM', current: '04:20 PM', delay: '+125 min', carrier: 'Ownfleet',   risk: 'Critical' },
    { orderId: 'ORD-DEL-1923913', store: 'STR-DEL-02 - Vasant Kunj',  city: 'Delhi NCR', customer: 'Raj Verma',     promised: '04:15 PM', current: '05:55 PM', delay: '+100 min', carrier: 'Ownfleet',   risk: 'High'     },
    { orderId: 'ORD-JAI-0312848', store: 'STR-JAI-01 - C-Scheme',     city: 'Jaipur',    customer: 'Pooja Jain',    promised: '02:45 PM', current: '05:10 PM', delay: '+145 min', carrier: 'Ownfleet',   risk: 'Critical' },
    { orderId: 'ORD-HYD-0847232', store: 'STR-HYD-01 - HITEC',        city: 'Hyderabad', customer: 'Rakesh Rao',    promised: '03:15 PM', current: '05:00 PM', delay: '+105 min', carrier: 'Shadowfax',  risk: 'High'     },
    { orderId: 'ORD-MUM-2847502', store: 'STR-MUM-02 - Thane',        city: 'Mumbai',    customer: 'Suresh Kumar',  promised: '04:45 PM', current: '06:20 PM', delay: '+95 min',  carrier: 'Shadowfax',  risk: 'Medium'   },
    { orderId: 'ORD-SUR-0123492', store: 'STR-SUR-01 - Ring Rd',      city: 'Surat',     customer: 'Neha Shah',     promised: '04:00 PM', current: '05:40 PM', delay: '+100 min', carrier: 'Delhivery',  risk: 'High'     },
    { orderId: 'ORD-DEL-1924082', store: 'STR-DEL-03 - Vasant Vihar', city: 'Delhi NCR', customer: 'Kunal Singh',   promised: '05:15 PM', current: '06:50 PM', delay: '+95 min',  carrier: 'Delhivery',  risk: 'Medium'   },
    { orderId: 'ORD-BLR-0918275', store: 'STR-BLR-01 - Whitefield',   city: 'Bangalore', customer: 'Divya Iyer',    promised: '05:45 PM', current: '07:05 PM', delay: '+80 min',  carrier: 'Borzo',      risk: 'Medium'   },
    { orderId: 'ORD-PUN-0429185', store: 'STR-PUN-02 - Koregaon',     city: 'Pune',      customer: 'Rahul Joshi',   promised: '06:15 PM', current: '07:30 PM', delay: '+75 min',  carrier: 'Rapido',     risk: 'Medium'   },
    { orderId: 'ORD-MUM-2847394', store: 'STR-MUM-01 - Andheri',      city: 'Mumbai',    customer: 'Vikas Dubey',   promised: '04:00 PM', current: '06:00 PM', delay: '+120 min', carrier: 'Ownfleet',   risk: 'Critical' },
    { orderId: 'ORD-DEL-1923849', store: 'STR-DEL-01 - Dwarka',       city: 'Delhi NCR', customer: 'Anjali Sharma', promised: '02:30 PM', current: '04:30 PM', delay: '+120 min', carrier: 'Ownfleet',   risk: 'Critical' },
  ],



  pendingCOD: [
    { store: 'STR-MUM-01 - Andheri',      city: 'Mumbai',    amount: 84250, orders: 47, oldest: '2026-07-13', daysOld: 2, status: 'Overdue'   },
    { store: 'STR-DEL-01 - Dwarka',       city: 'Delhi NCR', amount: 71840, orders: 38, oldest: '2026-07-14', daysOld: 1, status: 'Due Today' },
    { store: 'STR-HYD-01 - HITEC',        city: 'Hyderabad', amount: 63420, orders: 31, oldest: '2026-07-13', daysOld: 2, status: 'Overdue'   },
    { store: 'STR-DEL-02 - Vasant Kunj',  city: 'Delhi NCR', amount: 58900, orders: 29, oldest: '2026-07-14', daysOld: 1, status: 'Due Today' },
    { store: 'STR-MUM-02 - Thane',        city: 'Mumbai',    amount: 47320, orders: 24, oldest: '2026-07-12', daysOld: 3, status: 'Overdue'   },
    { store: 'STR-JAI-01 - C-Scheme',     city: 'Jaipur',    amount: 43890, orders: 21, oldest: '2026-07-14', daysOld: 1, status: 'Due Today' },
    { store: 'STR-BLR-01 - Whitefield',   city: 'Bangalore', amount: 38140, orders: 19, oldest: '2026-07-15', daysOld: 0, status: 'Pending'   },
    { store: 'STR-SUR-01 - Ring Rd',      city: 'Surat',     amount: 34780, orders: 17, oldest: '2026-07-14', daysOld: 1, status: 'Due Today' },
    { store: 'STR-DEL-03 - Vasant Vihar', city: 'Delhi NCR', amount: 28960, orders: 14, oldest: '2026-07-15', daysOld: 0, status: 'Pending'   },
    { store: 'STR-PUN-02 - Koregaon',     city: 'Pune',      amount: 10850, orders: 6,  oldest: '2026-07-15', daysOld: 0, status: 'Pending'   },
    { store: 'STR-MUM-01 - Andheri',      city: 'Mumbai',    amount: 81250, orders: 45, oldest: '2026-07-14', daysOld: 1, status: 'Due Today' },
    { store: 'STR-DEL-01 - Dwarka',       city: 'Delhi NCR', amount: 69840, orders: 36, oldest: '2026-07-15', daysOld: 0, status: 'Pending' },
    { store: 'STR-HYD-01 - HITEC',        city: 'Hyderabad', amount: 61420, orders: 30, oldest: '2026-07-14', daysOld: 1, status: 'Due Today' },
    { store: 'STR-DEL-02 - Vasant Kunj',  city: 'Delhi NCR', amount: 56900, orders: 27, oldest: '2026-07-15', daysOld: 0, status: 'Pending' },
    { store: 'STR-MUM-02 - Thane',        city: 'Mumbai',    amount: 45320, orders: 22, oldest: '2026-07-13', daysOld: 2, status: 'Overdue'   },
    { store: 'STR-JAI-01 - C-Scheme',     city: 'Jaipur',    amount: 41890, orders: 19, oldest: '2026-07-15', daysOld: 0, status: 'Pending' },
    { store: 'STR-BLR-01 - Whitefield',   city: 'Bangalore', amount: 36140, orders: 17, oldest: '2026-07-16', daysOld: -1, status: 'Pending' },
    { store: 'STR-SUR-01 - Ring Rd',      city: 'Surat',     amount: 32780, orders: 15, oldest: '2026-07-15', daysOld: 0, status: 'Pending' },
    { store: 'STR-DEL-03 - Vasant Vihar', city: 'Delhi NCR', amount: 26960, orders: 12, oldest: '2026-07-16', daysOld: -1, status: 'Pending' },
    { store: 'STR-PUN-02 - Koregaon',     city: 'Pune',      amount: 8850,  orders: 4,  oldest: '2026-07-16', daysOld: -1, status: 'Pending' },
    { store: 'STR-MUM-01 - Andheri',      city: 'Mumbai',    amount: 79250, orders: 42, oldest: '2026-07-15', daysOld: 0, status: 'Pending' },
  ],

  driverCOD: [
    { driverId: 'DRV-8349', store: 'STR-MUM-01 - Andheri',      city: 'Mumbai',    cashInHand: 12400, lastCollected: '02:30 PM', status: 'Pending' },
    { driverId: 'DRV-9122', store: 'STR-DEL-01 - Dwarka',       city: 'Delhi NCR', cashInHand: 8950,  lastCollected: '11:45 AM', status: 'Pending' },
    { driverId: 'DRV-1104', store: 'STR-MUM-02 - Thane',        city: 'Mumbai',    cashInHand: 15200, lastCollected: '01:15 PM', status: 'Pending' },
    { driverId: 'DRV-4421', store: 'STR-HYD-01 - HITEC',        city: 'Hyderabad', cashInHand: 9800,  lastCollected: '12:30 PM', status: 'Overdue' },
    { driverId: 'DRV-5092', store: 'STR-DEL-02 - Vasant Kunj',  city: 'Delhi NCR', cashInHand: 11050, lastCollected: '03:10 PM', status: 'Pending' },
    { driverId: 'DRV-3811', store: 'STR-BLR-01 - Whitefield',   city: 'Bangalore', cashInHand: 7400,  lastCollected: '04:00 PM', status: 'Pending' },
    { driverId: 'DRV-7719', store: 'STR-JAI-01 - C-Scheme',     city: 'Jaipur',    cashInHand: 14500, lastCollected: '10:00 AM', status: 'Overdue' },
    { driverId: 'DRV-6294', store: 'STR-SUR-01 - Ring Rd',      city: 'Surat',     cashInHand: 6200,  lastCollected: '02:45 PM', status: 'Pending' },
    { driverId: 'DRV-8402', store: 'STR-DEL-03 - Vasant Vihar', city: 'Delhi NCR', cashInHand: 5100,  lastCollected: '05:30 PM', status: 'Pending' },
    { driverId: 'DRV-2947', store: 'STR-PUN-02 - Koregaon',     city: 'Pune',      cashInHand: 8300,  lastCollected: '11:15 AM', status: 'Pending' },
    { driverId: 'DRV-8350', store: 'STR-MUM-01 - Andheri',      city: 'Mumbai',    cashInHand: 11400, lastCollected: '02:45 PM', status: 'Pending' },
    { driverId: 'DRV-9123', store: 'STR-DEL-01 - Dwarka',       city: 'Delhi NCR', cashInHand: 7950,  lastCollected: '12:00 PM', status: 'Pending' },
    { driverId: 'DRV-1105', store: 'STR-MUM-02 - Thane',        city: 'Mumbai',    cashInHand: 14200, lastCollected: '01:30 PM', status: 'Pending' },
    { driverId: 'DRV-4422', store: 'STR-HYD-01 - HITEC',        city: 'Hyderabad', cashInHand: 8800,  lastCollected: '12:45 PM', status: 'Due Today' },
    { driverId: 'DRV-5093', store: 'STR-DEL-02 - Vasant Kunj',  city: 'Delhi NCR', cashInHand: 10050, lastCollected: '03:25 PM', status: 'Pending' },
    { driverId: 'DRV-3812', store: 'STR-BLR-01 - Whitefield',   city: 'Bangalore', cashInHand: 6400,  lastCollected: '04:15 PM', status: 'Pending' },
    { driverId: 'DRV-7720', store: 'STR-JAI-01 - C-Scheme',     city: 'Jaipur',    cashInHand: 13500, lastCollected: '10:15 AM', status: 'Due Today' },
    { driverId: 'DRV-6295', store: 'STR-SUR-01 - Ring Rd',      city: 'Surat',     cashInHand: 5200,  lastCollected: '03:00 PM', status: 'Pending' },
    { driverId: 'DRV-8403', store: 'STR-DEL-03 - Vasant Vihar', city: 'Delhi NCR', cashInHand: 4100,  lastCollected: '05:45 PM', status: 'Pending' },
    { driverId: 'DRV-2948', store: 'STR-PUN-02 - Koregaon',     city: 'Pune',      cashInHand: 7300,  lastCollected: '11:30 AM', status: 'Pending' },
    { driverId: 'DRV-8351', store: 'STR-MUM-01 - Andheri',      city: 'Mumbai',    cashInHand: 10400, lastCollected: '03:00 PM', status: 'Pending' },
  ],

  driverCompliance: [
    { driverId: 'DRV-8349', store: 'STR-MUM-01 - Andheri',      city: 'Mumbai',    partialCod: 2, rejectedOrders: 5, locationMismatch: 3, podNonCompliant: 1 },
    { driverId: 'DRV-9122', store: 'STR-DEL-01 - Dwarka',       city: 'Delhi NCR', partialCod: 0, rejectedOrders: 2, locationMismatch: 1, podNonCompliant: 0 },
    { driverId: 'DRV-1104', store: 'STR-MUM-02 - Thane',        city: 'Mumbai',    partialCod: 1, rejectedOrders: 3, locationMismatch: 0, podNonCompliant: 2 },
    { driverId: 'DRV-4421', store: 'STR-HYD-01 - HITEC',        city: 'Hyderabad', partialCod: 3, rejectedOrders: 6, locationMismatch: 4, podNonCompliant: 1 },
    { driverId: 'DRV-5092', store: 'STR-DEL-02 - Vasant Kunj',  city: 'Delhi NCR', partialCod: 0, rejectedOrders: 1, locationMismatch: 0, podNonCompliant: 0 },
    { driverId: 'DRV-3811', store: 'STR-BLR-01 - Whitefield',   city: 'Bangalore', partialCod: 1, rejectedOrders: 2, locationMismatch: 2, podNonCompliant: 0 },
    { driverId: 'DRV-7719', store: 'STR-JAI-01 - C-Scheme',     city: 'Jaipur',    partialCod: 2, rejectedOrders: 4, locationMismatch: 1, podNonCompliant: 3 },
    { driverId: 'DRV-6294', store: 'STR-SUR-01 - Ring Rd',      city: 'Surat',     partialCod: 0, rejectedOrders: 0, locationMismatch: 0, podNonCompliant: 0 },
    { driverId: 'DRV-8402', store: 'STR-DEL-03 - Vasant Vihar', city: 'Delhi NCR', partialCod: 1, rejectedOrders: 1, locationMismatch: 1, podNonCompliant: 1 },
    { driverId: 'DRV-2947', store: 'STR-PUN-02 - Koregaon',     city: 'Pune',      partialCod: 0, rejectedOrders: 3, locationMismatch: 2, podNonCompliant: 0 },
    { driverId: 'DRV-8350', store: 'STR-MUM-01 - Andheri',      city: 'Mumbai',    partialCod: 1, rejectedOrders: 4, locationMismatch: 2, podNonCompliant: 0 },
    { driverId: 'DRV-9123', store: 'STR-DEL-01 - Dwarka',       city: 'Delhi NCR', partialCod: 0, rejectedOrders: 1, locationMismatch: 0, podNonCompliant: 0 },
    { driverId: 'DRV-1105', store: 'STR-MUM-02 - Thane',        city: 'Mumbai',    partialCod: 0, rejectedOrders: 2, locationMismatch: 0, podNonCompliant: 1 },
    { driverId: 'DRV-4422', store: 'STR-HYD-01 - HITEC',        city: 'Hyderabad', partialCod: 2, rejectedOrders: 5, locationMismatch: 3, podNonCompliant: 0 },
    { driverId: 'DRV-5093', store: 'STR-DEL-02 - Vasant Kunj',  city: 'Delhi NCR', partialCod: 0, rejectedOrders: 0, locationMismatch: 0, podNonCompliant: 0 },
    { driverId: 'DRV-3812', store: 'STR-BLR-01 - Whitefield',   city: 'Bangalore', partialCod: 1, rejectedOrders: 1, locationMismatch: 1, podNonCompliant: 0 },
    { driverId: 'DRV-7720', store: 'STR-JAI-01 - C-Scheme',     city: 'Jaipur',    partialCod: 1, rejectedOrders: 3, locationMismatch: 0, podNonCompliant: 2 },
    { driverId: 'DRV-6295', store: 'STR-SUR-01 - Ring Rd',      city: 'Surat',     partialCod: 0, rejectedOrders: 0, locationMismatch: 0, podNonCompliant: 0 },
    { driverId: 'DRV-8403', store: 'STR-DEL-03 - Vasant Vihar', city: 'Delhi NCR', partialCod: 0, rejectedOrders: 0, locationMismatch: 1, podNonCompliant: 0 },
    { driverId: 'DRV-2948', store: 'STR-PUN-02 - Koregaon',     city: 'Pune',      partialCod: 0, rejectedOrders: 2, locationMismatch: 1, podNonCompliant: 0 },
    { driverId: 'DRV-8351', store: 'STR-MUM-01 - Andheri',      city: 'Mumbai',    partialCod: 0, rejectedOrders: 3, locationMismatch: 1, podNonCompliant: 0 },
  ]
};
